version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backended:
    image: go-containerized
    restart: "no"
    ports:
      - 8000:8000
    environment:
      DB_NAME: kisahnesia
      DB_PASSWORD: example
      DB_USERNAME: postgres
      DB_ADDRESS: db
      KEY: bapakmu
      salt: b1pa7m2

