DROP TABLE IF EXISTS "isi";

DROP SEQUENCE IF EXISTS "isi_id_seq";

DROP TABLE IF EXISTS "cerita";

DROP SEQUENCE IF EXISTS "cerita_id_seq";

DROP TABLE IF EXISTS "user";

DROP SEQUENCE IF EXISTS "user_id_seq";

DROP FUNCTION IF EXISTS "update_modified_column";